- name:  set up prompt
  ansible.builtin.shell: set-hostname {{ component }}

- name: Setup the {{ component }} repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install {{ component }}
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Start & Enable {{ component }} Service
  ansible.builtin.shell: |
    systemctl enable mongod 
    systemctl start mongod 

- name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  ansible.builtin.shell: sed  -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf

- name: Restart  {{ component }} Service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
