- name:  set up prompt
  ansible.builtin.shell: set-hostname {{ component }}

- name: To install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy configuration file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

#- name: Clean Up old {{ component }}
#  ansible.builtin.shell: rm -rf *
#  args:
#    chdir: /usr/share/nginx/html
#
#- name: Download new {{ component }} content
#  ansible.builtin.unarchive:
#    src: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /usr/share/nginx/html/
#    remote_src: yes

- name: Import content-download role from common
  ansible.builtin.import_role:
    name: common
    tasks_from: content-download
  vars:
    path: /usr/share/nginx/html

- name: Start {{ component }} service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: true
  tags: restarted
