- name: Clean Up old {{ component }} content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Lets setup an app directory.
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download the {{ component }} code to created app directory
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes



