- name:  set up prompt
  ansible.builtin.shell: set-hostname {{ component }}

- name: ansible {{ component }} include app-preq tasks
  ansible.builtin.include_tasks:
    file: app-preq.yml

- name: ansible {{ component }} include content-download tasks
  ansible.builtin.include_tasks:
    file: content-download.yml
  vars:
    path: /app

- name: ansible {{ component }} include mongodb-client tasks
  ansible.builtin.include_tasks:
    file: mongodb-client.yml